### ISSUE TITLE
Share SQL file

### ISSUE THREAD

**Issue by MdMirajAnsari** [mrnikhilsingh/coffee-shop-management-system#1]
Please share the SQL file for the database .

**Comment by mrnikhilsingh** [comment]
The SQL file for the database has already been added to the repository. 

You can find it here [ https://github.com/mrnikhilsingh/coffee-shop-management-system/blob/main/db/ns_coffee.sql ] (link-to-sql-file). 

Please let me know if you need any further assistance!
